kind: pipeline
type: kubernetes
name: default

steps:
  - name: build
    image: quay.io/buildah/stable:latest
    environment:
      # get registry credentials from orgsecrets
      REGISTRY_USERNAME:
        from_secret: registry_username
      REGISTRY_PASSWORD:
        from_secret: registry_password
      # get GPG key from orgsecrets
      GPG_KEY:
        from_secret: gpg_key
    # can't find a way to get buildah to work right with fuse-overlayfs in unprivileged mode
    privileged: true
    # only fire on tags/releases
    trigger:
      event:
        - tag
    commands:
      - echo -e $GPG_KEY > gpg.key
      - buildah login -u $REGISTRY_USERNAME -p $REGISTRY_PASSWORD registry.hubbe.club
      - buildah bud --tag registry.hubbe.club/autoapply:$DRONE_TAG .
      - buildah push registry.hubbe.club/autoapply:$DRONE_TAG
    resources:
      requests:
        cpu: 100
        memory: 100MiB
      limits:
        cpu: 500
        memory: 500MiB
