apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: autoapply
spec:
  schedule: "*/5 * * * *"
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          serviceAccountName: autoapply
          containers:
            - name: autoapply
              image: $IMAGE_TAG
              env:
                - name: SOPS_PGP_FP
                  valueFrom:
                    secretKeyRef:
                      name: gpg-secrets
                      key: GPG_FINGERPRINT
                - name: GPG_PASSPHRASE
                  valueFrom:
                    secretKeyRef:
                      name: gpg-secrets
                      key: GPG_PASSPHRASE
              resources:
                requests:
                  cpu: "50m"
                  memory: "50Mi"
              command: ["bash"]
              args: ["/apply.sh"]
              volumeMounts:
                - name: apply-script
                  mountPath: /apply.sh
                  subPath: apply.sh
                - name: gpg-key
                  mountPath: /gpg.key
                  subPath: gpg.key
          volumes:
            - name: apply-script
              configMap:
                name: apply-script
                defaultMode: 0755
            - name: gpg-key
              secret:
                secretName: gpg-secrets
